<?php
$randomThings = array(
    'Jesus Christ',    
    'yolo swag',    
    'lord satan',    
    'fucker',    
    'help me',    
    'Sebastian',    
    'damned',
    'America',
    'van Gogh',
    'fuckbot',
    'fuckboy',
    '666',
    'head honcho',
    'slime queen',
    'Porpentine',
    'Abraham Lincoln',
    'goddess',
    'Macbeth',
    'Isabella',
    'William Shakespeare',
    'satan',
    'bill clinton',
    'sweg',
    'bigmac',
    'Zac',
    'rumplestiltskin',
);

?>
